version: '3'

services:

  bitcoind-testnet:
    container_name: bitcoind_rpc_testnet
    build: containers/btc
    restart: always
    ports:
#      - "8301:8332" # mainnet-rpc
      - "8401:18332" # testnet-rpc
#      - "28332:28332" # zmq
    environment:
      PRINTTOCONSOLE: 1
      DISABLEWALLET: 0
      RPCUSER: test
      RPCPASSWORD: test
      SERVICE_NAME: bitcoind_testnet_service
      SERVICE_TAGS: bitcoind_testnet
    command: "-testnet -prune=10000 -rpcuser=test -rpcpassword=test -rpcallowip=::/0 -zmqpubrawtx=tcp://0.0.0.0:28332 -zmqpubrawblock=tcp://0.0.0.0:28332 -zmqpubhashblock=tcp://0.0.0.0:28332 -zmqpubhashtx=tcp://0.0.0.0:28332"
    volumes:
      - "bitcoin_testnet_data:/bitcoin-testnet"
    networks:
      app_net:
        ipv4_address: 172.16.238.101
#    healthcheck:
#      test: ["CMD", "curl", "-f", "http://localhost:18332/"]
#      interval: 10s
#      timeout: 10s
#      retries: 3
    dns_search: consul_server


  bitcoind:
    container_name: bitcoind_rpc
    build: containers/btc
    restart: always
    ports:
      - "8301:8332" # mainnet-rpc
#      - "8401:18332" # testnet-rpc
#      - "28332:28332" # zmq
    environment:
      PRINTTOCONSOLE: 1
      DISABLEWALLET: 0
      RPCUSER: test
      RPCPASSWORD: test
      SERVICE_NAME: bitcoind_service
      SERVICE_TAGS: bitcoind
    command: "-prune=10000 -rpcuser=test -rpcpassword=test -rpcallowip=::/0 -zmqpubrawtx=tcp://0.0.0.0:28332 -zmqpubrawblock=tcp://0.0.0.0:28332 -zmqpubhashblock=tcp://0.0.0.0:28332 -zmqpubhashtx=tcp://0.0.0.0:28332"
    volumes:
      - "bitcoin_data:/bitcoin"
    networks:
      app_net:
        ipv4_address: 172.16.238.102
#    healthcheck:
#      test: ["CMD", "curl", "-f", "http://localhost:18332/"]
#      interval: 10s
#      timeout: 10s
#      retries: 3
    dns_search: consul_server


  #  litecoind:
  #    container_name: litecoind_rpc
  #    build: containers/ltc
  #    restart: always
  #    ports:
  #      - "8302:9332" # mainnet-rpc
  #      - "8402:19332" # testnet-rpc
  #    command: "-testnet -rpcuser=test -rpcpassword=test -rpcallowip=::/0"
  #    volumes:
  #      - "${BLOCKCHAIN_DATA_DIR}/litecoin:/home/litecoin/.litecoin"
  #    networks:
  #      app_net:
  #        ipv4_address: 172.16.238.102
  #    healthcheck:
  #      test: ["CMD", "curl", "-f", "http://localhost:19332/"]
  #      interval: 10s
  #      timeout: 10s
  #      retries: 3
  #    environment:
  #      SERVICE_NAME: litecoind_service
  #      SERVICE_TAGS: litecoind
  #    dns_search: consul_server
  #

  geth-rinkeby:
    container_name: geth_rinkeby_rpc
    build: containers/eth
    restart: always
    ports:
      - "8303:8545" # rpc
    command: "--rinkeby --debug --rpc --rpcport 8545 --rpcaddr 0.0.0.0 --rpccorsdomain \"*\" --rpcapi \"eth,web3\""
    volumes:
      - ethereum_rinkeby_data:/root
    networks:
      app_net:
        ipv4_address: 172.16.238.111
#    healthcheck:
#      test: ["CMD", "curl", "-f", "http://localhost:8545/"]
#      interval: 10s
#      timeout: 10s
#      retries: 3
    dns_search: consul_server
    environment:
      SERVICE_NAME: geth_rinkeby_service
      SERVICE_TAGS: geth_rinkeby

  #  rippled:
  #    container_name: rippled_rpc
  #    restart: always
  #    build: containers/xrp
  #    ports:
  #      - "8304:51234" # rpc
  #    volumes:
  #      - "${BLOCKCHAIN_DATA_DIR}/ripple:/var/lib/rippled"
  #    networks:
  #      app_net:
  #        ipv4_address: 172.16.238.104
  #    healthcheck:
  #      test: ["CMD", "curl", "-f", "http://localhost:51234/"]
  #      interval: 10s
  #      timeout: 10s
  #      retries: 3
  #    dns_search: consul_server
  #    environment:
  #      SERVICE_NAME: rippled_service
  #      SERVICE_TAGS: rippled


  consul:
    container_name: consul_server
    image: consul:latest
    restart: always
    volumes:
      - "./data/consul/config:/consul/config"
    command: agent -server -dev -ui -bind 0.0.0.0 -client 0.0.0.0 -bootstrap-expect=1
    ports:
      - "9501:8500"  # ui
      - "9601:8400"  # rpc/rest
      - "54:53/udp"   # dns
    networks:
      app_net:
        ipv4_address: 172.16.238.201
    environment:
      SERVICE_NAME: consul_server_service
      SERVICE_TAGS: consul

  registrator:
    container_name: registrator
    restart: always
    command: consul://172.16.238.201:8500
    image: gliderlabs/registrator:latest
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock"
    links:
      - consul
    networks:
      app_net:
        ipv4_address: 172.16.238.202



networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24

volumes:
  bitcoin_testnet_data:
    driver: local-persist
    driver_opts:
      mountpoint: /mnt/bitcoind-testnet

  bitcoin_data:
    driver: local-persist
    driver_opts:
      mountpoint: /mnt/bitcoind-mainnet

  ethereum_rinkeby_data:
    driver: local-persist
    driver_opts:
      mountpoint: /mnt/geth-testnet
